parameters:
    pim_datagrid.event_subscriber.default_view.class: Oro\Bundle\PimDataGridBundle\EventSubscriber\DefaultViewSubscriber
    pim_datagrid.event_subscriber.filter_entity_with_values_subscriber.class: Oro\Bundle\PimDataGridBundle\EventSubscriber\FilterEntityWithValuesSubscriber

services:
    pim_datagrid.event_subscriber.default_view:
        class: '%pim_datagrid.event_subscriber.default_view.class%'
        arguments:
            - '@pim_datagrid.repository.datagrid_view'
        tags:
            - { name: kernel.event_subscriber }

    pim_datagrid.event_subscriber.filter_entity_with_values_subscriber:
        class: '%pim_datagrid.event_subscriber.filter_entity_with_values_subscriber.class%'
        tags:
            - { name: doctrine.event_subscriber, priority: 100 }
