parameters:
  pim_user.provider.user.class: Akeneo\UserManagement\Bundle\Security\UserProvider

services:
  pim_user.provider.user:
    class: '%pim_user.provider.user.class%'
    arguments:
      - '@pim_user.repository.user'
