parameters:
    pim_user.query.is_there_user_without_role.class: Akeneo\UserManagement\Bundle\Doctrine\ORM\Query\IsThereUserWithoutRole

services:
    pim_user.query.is_there_user_without_role:
        class: '%pim_user.query.is_there_user_without_role.class%'
        arguments:
        - '@doctrine.orm.entity_manager'
