liip_imagine:
    data_loader: flysystem_data_loader
    filter_sets:
        avatar_med:
            quality:          95
            format:           png
            filters:
                thumbnail:    { size: [58, 58], mode: outbound }
                strip:        ~
        preview:
            quality:          95
            format:           jpg
            filters:
                background:
                    color: "#ffffff"
                strip:        ~
        thumbnail:
            quality:          95
            format:           png
            filters:
                thumbnail:    { size: [320, 320], mode: outbound }
                strip:        ~
        thumbnail_small:
            quality:          95
            format:           png
            filters:
                thumbnail:    { size: [280, 280], mode: outbound }
                strip:        ~
        pdf_thumbnail:
            quality:          95
            format:           png
            filters:
                downscale: { max: [320, 240] }
                strip:        ~
