parameters:
    pim_enrich.filter.product_edit_data.class: Pim\Bundle\EnrichBundle\Filter\ProductEditDataFilter
    pim_enrich.filter.product_values_edit_data.class: Pim\Bundle\EnrichBundle\Filter\ProductValuesEditDataFilter

services:
    pim_enrich.filter.product_edit_data:
        class: '%pim_enrich.filter.product_edit_data.class%'
        arguments:
            - '@oro_security.security_facade'
            - '@pim_enrich.filter.product_values_edit_data'

    pim_enrich.filter.product_values_edit_data:
        class: '%pim_enrich.filter.product_values_edit_data.class%'
        arguments:
            - '@pim_catalog.filter.chained'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.repository.channel'

    pim_enrich.filter.product_attribute_filter:
        class: 'Akeneo\Pim\Enrichment\Component\Product\ProductModel\Filter\ProductAttributeFilter'
        arguments:
            - '@pim_catalog.repository.product_model'
            - '@pim_catalog.repository.cached_family'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.cached_attribute'

    pim_enrich.filter.product_model_attribute_filter:
        class: 'Akeneo\Pim\Enrichment\Component\Product\ProductModel\Filter\ProductModelAttributeFilter'
        arguments:
            - '@pim_catalog.repository.family_variant'
            - '@pim_catalog.repository.product_model'
            - '@pim_catalog.repository.cached_attribute'
