parameters:
    pim_enrich.writer.database.product_and_product_model_writer.class: Pim\Bundle\EnrichBundle\Connector\Writer\MassEdit\ProductAndProductModelWriter

services:
    pim_enrich.writer.database.product_and_product_model_writer:
        class: '%pim_enrich.writer.database.product_and_product_model_writer.class%'
        arguments:
            - '@pim_versioning.manager.version'
            - '@pim_catalog.saver.product'
            - '@pim_catalog.saver.product_model'
            - '@security.token_storage'
            - '@akeneo_batch_queue.launcher.queue_job_launcher'
            - '@akeneo_batch.job.job_instance_repository'
            - '%pim_catalog.compute_product_models_descendants.job_name%'
