services:
    pim_comment.normalizer.standard.comment:
        class: 'Akeneo\Pim\Enrichment\Component\Comment\Normalizer\Standard\CommentNormalizer'
        tags:
            - { name: pim_standard_format_serializer.normalizer, priority: 90 }

    pim_api.normalizer.product:
        class: 'Akeneo\Pim\Enrichment\Component\Product\Normalizer\ExternalApi\ProductNormalizer'
        arguments:
            - '@pim_catalog.normalizer.standard.product'
            - '@pim_api.repository.attribute'
            - '@router'
        tags:
            - { name: pim_external_api_serializer.normalizer, priority: 90 }

    pim_api.normalizer.product_model:
        class: 'Akeneo\Pim\Enrichment\Component\Product\Normalizer\ExternalApi\ProductModelNormalizer'
        arguments:
            - '@pim_catalog.normalizer.standard.product_model'
            - '@pim_api.repository.attribute'
            - '@router'
        tags:
            - { name: pim_external_api_serializer.normalizer, priority: 90 }

    pim_api.normalizer.category:
        class: 'Akeneo\Pim\Enrichment\Component\Category\Normalizer\ExternalApi\CategoryNormalizer'
        arguments:
            - '@pim_catalog.normalizer.standard.category'
        tags:
            - { name: pim_external_api_serializer.normalizer, priority: 90 }
