product:
    resource: '@AkeneoPimEnrichmentBundle/Resources/config/routing/product.yml'
    prefix: /enrich/product

comment:
    resource: '@AkeneoPimEnrichmentBundle/Resources/config/routing/comment.yml'

localization:
    resource: '@AkeneoPimEnrichmentBundle/Resources/config/routing/localization.yml'

external_api_product_model:
    resource: '@AkeneoPimEnrichmentBundle/Resources/config/routing/external_api/product_model.yml'
    prefix: /api/rest/v1

external_api_category:
    resource: '@AkeneoPimEnrichmentBundle/Resources/config/routing/external_api/category.yml'
    prefix: /api/rest/v1

external_api_product:
    resource: '@AkeneoPimEnrichmentBundle/Resources/config/routing/external_api/product.yml'
    prefix: /api/rest/v1
